server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  # model的包
  type-aliases-package: com.demo.entity
#  configuration:
  # 开启驼峰uName自动映射到u_name
#  map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
    com.demo.dao : debug